workflowsworkflows:
  build-telegram:
    name: Build Telegram Android
    max_build_duration: 60
    environment:
      vars:
        RELEASE_STORE_FILE: TMessagesProj/config/release.keystore
        RELEASE_KEY_ALIAS: telegram
        RELEASE_STORE_PASSWORD: 123456
        RELEASE_KEY_PASSWORD: 123456
    scripts:
      - name: تحديث مكتبات C/C++
        script: |
          git submodule update --init --recursive
      - name: إنشاء ملف google-services.json
        script: |
          echo '{}' > TMessagesProj/google-services.json
      - name: إنشاء keystore وهمي
        script: |
          mkdir -p TMessagesProj/config
          keytool -genkeypair \
            -storetype JKS \
            -keystore $RELEASE_STORE_FILE \
            -storepass $RELEASE_STORE_PASSWORD \
            -alias $RELEASE_KEY_ALIAS \
            -keypass $RELEASE_KEY_PASSWORD \
            -dname "CN=Telegram,O=Org,C=US" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000
      - name: بناء التطبيق
        script: |
          ./gradlew :TMessagesProj:assemblePlayRelease \
            -Pandroid.injected.signing.store.file=$RELEASE_STORE_FILE \
            -Pandroid.injected.signing.store.password=$RELEASE_STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$RELEASE_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$RELEASE_KEY_PASSWORD
    artifacts:
      - TMessagesProj/build/outputs/**/*.apk
